[workspace]
members = [
  "tokengen-core",
  "tokengen-cli",
  "tokengen-web"
]
resolver = "2"
[workspace.package]
version = "0.1.0"
description = "funny tokengen library"
edition = "2021"
license = "MIT"
repository = "https://github.com/Ecorous/tokengen-rs"