[package]
name = "tokengen-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokengen-core = { version = "0.1.0", path = "../tokengen-core"}